openapi: 3.0.0
info:
  version: "1.0"
  title: API-TD Onboardin STD22087
servers:
  - url: http://STD22087.com
paths:
  /students:
    get:
      summary: Récupère les informations d'un étudiant.
      responses:
        '200':
          description: Succès. Renvoie les informations de l'étudiant.
          content:
            application/json:
              example:
                nom: Nom de l'étudiant 'Ravohitsoa'
                prénom: Prénom de l'étudiant'Allan'
                STD: Matricule de l'étudiant 'STD22087'
        '500'
          description: Erreur. Renvoie un message d'erreur.

    post:
      summary: Ajoute un nouvel étudiant.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nom:
                  type: string
                prénom:
                  type: string
                STD:
                  type: string
      responses:
        '200':
          description: Succès. Renvoie les informations de l'étudiant ajouté.
          content:
            application/json:
              example:
                nom: Nom de l'étudiant ajouté
                prénom: Prénom de l'étudiant ajouté
                STD: Matricule de l'étudiant ajouté
        '500':
          description: Erreur. Renvoie un message d'erreur.
